package com.kivora.JsWater.domain.model.notification;

public enum NotificationType {
    INVOICE_GENERATED,
    INVOICE_REMINDER_7_DAYS,
    INVOICE_REMINDER_1_DAY,
    PAYMENT_CONFIRMED,
    INVOICE_LATE,
    INVOICE_CUTOFF_WARNING,

    READING_CONFIRMED,
    ABNORMAL_CONSUMPTION,
    MISSING_READING,

    METER_INSTALLED,
    METER_REPLACED,
    METER_FAILURE,
    METER_MAINTENANCE,

    LOGIN_NEW_DEVICE,
    PASSWORD_CHANGED,
    PROFILE_CHANGED,
    LOGIN_FAILED_ATTEMPTS,

    SERVICE_OUTAGE_PLANNED,
    SERVICE_OUTAGE_UNPLANNED,
    SERVICE_RESTORED,

    TARIFF_CHANGE,
    POLICY_UPDATE
}
